# automatically generated by the FlatBuffers compiler, do not modify
# Extended with all fields from config.fbs schema

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GenerationConfiguration(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GenerationConfiguration()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGenerationConfiguration(cls, buf, offset=0):
        """Deprecated, please use GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # GenerationConfiguration
    def Init(self, buf, pos):
        self._tab = flatbuffers.Table(buf, pos)

    # Slot 0: id (long)
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Slot 1: start_width (ushort)
    def StartWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Slot 2: start_height (ushort)
    def StartHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Slot 3: seed (uint)
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Slot 4: steps (uint)
    def Steps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Slot 5: guidance_scale (float)
    def GuidanceScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Slot 6: strength (float)
    def Strength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Slot 7: model (string)
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Slot 8: sampler (SamplerType byte)
    def Sampler(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Slot 9: batch_count (uint, default 1)
    def BatchCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1

    # Slot 10: batch_size (uint, default 1)
    def BatchSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1


# ============================================================================
# Field count: 84 fields total (slots 0-83) matching config.fbs
# ============================================================================

def GenerationConfigurationStart(builder):
    builder.StartObject(84)

def Start(builder):
    GenerationConfigurationStart(builder)

def GenerationConfigurationEnd(builder):
    return builder.EndObject()

def End(builder):
    return GenerationConfigurationEnd(builder)

# --- Slot 0: id (long) ---
def GenerationConfigurationAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    GenerationConfigurationAddId(builder, id)

# --- Slot 1: start_width (ushort) ---
def GenerationConfigurationAddStartWidth(builder, startWidth):
    builder.PrependUint16Slot(1, startWidth, 0)

def AddStartWidth(builder, startWidth):
    GenerationConfigurationAddStartWidth(builder, startWidth)

# --- Slot 2: start_height (ushort) ---
def GenerationConfigurationAddStartHeight(builder, startHeight):
    builder.PrependUint16Slot(2, startHeight, 0)

def AddStartHeight(builder, startHeight):
    GenerationConfigurationAddStartHeight(builder, startHeight)

# --- Slot 3: seed (uint) ---
def GenerationConfigurationAddSeed(builder, seed):
    builder.PrependUint32Slot(3, seed, 0)

def AddSeed(builder, seed):
    GenerationConfigurationAddSeed(builder, seed)

# --- Slot 4: steps (uint) ---
def GenerationConfigurationAddSteps(builder, steps):
    builder.PrependUint32Slot(4, steps, 0)

def AddSteps(builder, steps):
    GenerationConfigurationAddSteps(builder, steps)

# --- Slot 5: guidance_scale (float) ---
def GenerationConfigurationAddGuidanceScale(builder, guidanceScale):
    builder.PrependFloat32Slot(5, guidanceScale, 0.0)

def AddGuidanceScale(builder, guidanceScale):
    GenerationConfigurationAddGuidanceScale(builder, guidanceScale)

# --- Slot 6: strength (float) ---
def GenerationConfigurationAddStrength(builder, strength):
    builder.PrependFloat32Slot(6, strength, 0.0)

def AddStrength(builder, strength):
    GenerationConfigurationAddStrength(builder, strength)

# --- Slot 7: model (string) ---
def GenerationConfigurationAddModel(builder, model):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(model), 0)

def AddModel(builder, model):
    GenerationConfigurationAddModel(builder, model)

# --- Slot 8: sampler (SamplerType byte) ---
def GenerationConfigurationAddSampler(builder, sampler):
    builder.PrependUint8Slot(8, sampler, 0)

def AddSampler(builder, sampler):
    GenerationConfigurationAddSampler(builder, sampler)

# --- Slot 9: batch_count (uint, default 1) ---
def GenerationConfigurationAddBatchCount(builder, batchCount):
    builder.PrependUint32Slot(9, batchCount, 1)

def AddBatchCount(builder, batchCount):
    GenerationConfigurationAddBatchCount(builder, batchCount)

# --- Slot 10: batch_size (uint, default 1) ---
def GenerationConfigurationAddBatchSize(builder, batchSize):
    builder.PrependUint32Slot(10, batchSize, 1)

def AddBatchSize(builder, batchSize):
    GenerationConfigurationAddBatchSize(builder, batchSize)

# --- Slot 11: hires_fix (bool) ---
def GenerationConfigurationAddHiresFix(builder, hiresFix):
    builder.PrependBoolSlot(11, hiresFix, 0)

def AddHiresFix(builder, hiresFix):
    GenerationConfigurationAddHiresFix(builder, hiresFix)

# --- Slot 12: hires_fix_start_width (ushort) ---
def GenerationConfigurationAddHiresFixStartWidth(builder, hiresFixStartWidth):
    builder.PrependUint16Slot(12, hiresFixStartWidth, 0)

def AddHiresFixStartWidth(builder, hiresFixStartWidth):
    GenerationConfigurationAddHiresFixStartWidth(builder, hiresFixStartWidth)

# --- Slot 13: hires_fix_start_height (ushort) ---
def GenerationConfigurationAddHiresFixStartHeight(builder, hiresFixStartHeight):
    builder.PrependUint16Slot(13, hiresFixStartHeight, 0)

def AddHiresFixStartHeight(builder, hiresFixStartHeight):
    GenerationConfigurationAddHiresFixStartHeight(builder, hiresFixStartHeight)

# --- Slot 14: hires_fix_strength (float, default 0.7) ---
def GenerationConfigurationAddHiresFixStrength(builder, hiresFixStrength):
    builder.PrependFloat32Slot(14, hiresFixStrength, 0.7)

def AddHiresFixStrength(builder, hiresFixStrength):
    GenerationConfigurationAddHiresFixStrength(builder, hiresFixStrength)

# --- Slot 15: upscaler (string) ---
def GenerationConfigurationAddUpscaler(builder, upscaler):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(upscaler), 0)

def AddUpscaler(builder, upscaler):
    GenerationConfigurationAddUpscaler(builder, upscaler)

# --- Slot 16: image_guidance_scale (float, default 1.5) ---
def GenerationConfigurationAddImageGuidanceScale(builder, imageGuidanceScale):
    builder.PrependFloat32Slot(16, imageGuidanceScale, 1.5)

def AddImageGuidanceScale(builder, imageGuidanceScale):
    GenerationConfigurationAddImageGuidanceScale(builder, imageGuidanceScale)

# --- Slot 17: seed_mode (SeedMode byte) ---
def GenerationConfigurationAddSeedMode(builder, seedMode):
    builder.PrependUint8Slot(17, seedMode, 0)

def AddSeedMode(builder, seedMode):
    GenerationConfigurationAddSeedMode(builder, seedMode)

# --- Slot 18: clip_skip (uint, default 1) ---
def GenerationConfigurationAddClipSkip(builder, clipSkip):
    builder.PrependUint32Slot(18, clipSkip, 1)

def AddClipSkip(builder, clipSkip):
    GenerationConfigurationAddClipSkip(builder, clipSkip)

# --- Slot 19: controls ([Control]) ---
def GenerationConfigurationStartControlsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartControlsVector(builder, numElems):
    return GenerationConfigurationStartControlsVector(builder, numElems)

def GenerationConfigurationAddControls(builder, controls):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(controls), 0)

def AddControls(builder, controls):
    GenerationConfigurationAddControls(builder, controls)

# --- Slot 20: loras ([LoRA]) ---
def GenerationConfigurationStartLorasVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLorasVector(builder, numElems):
    return GenerationConfigurationStartLorasVector(builder, numElems)

def GenerationConfigurationAddLoras(builder, loras):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(loras), 0)

def AddLoras(builder, loras):
    GenerationConfigurationAddLoras(builder, loras)

# --- Slot 21: mask_blur (float) ---
def GenerationConfigurationAddMaskBlur(builder, maskBlur):
    builder.PrependFloat32Slot(21, maskBlur, 0.0)

def AddMaskBlur(builder, maskBlur):
    GenerationConfigurationAddMaskBlur(builder, maskBlur)

# --- Slot 22: face_restoration (string) ---
def GenerationConfigurationAddFaceRestoration(builder, faceRestoration):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(faceRestoration), 0)

def AddFaceRestoration(builder, faceRestoration):
    GenerationConfigurationAddFaceRestoration(builder, faceRestoration)

# --- Slot 23: decode_with_attention (bool, default true, deprecated) ---
def GenerationConfigurationAddDecodeWithAttention(builder, decodeWithAttention):
    builder.PrependBoolSlot(23, decodeWithAttention, 1)

def AddDecodeWithAttention(builder, decodeWithAttention):
    GenerationConfigurationAddDecodeWithAttention(builder, decodeWithAttention)

# --- Slot 24: hires_fix_decode_with_attention (bool, default true, deprecated) ---
def GenerationConfigurationAddHiresFixDecodeWithAttention(builder, val):
    builder.PrependBoolSlot(24, val, 1)

def AddHiresFixDecodeWithAttention(builder, val):
    GenerationConfigurationAddHiresFixDecodeWithAttention(builder, val)

# --- Slot 25: clip_weight (float, default 1) ---
def GenerationConfigurationAddClipWeight(builder, clipWeight):
    builder.PrependFloat32Slot(25, clipWeight, 1.0)

def AddClipWeight(builder, clipWeight):
    GenerationConfigurationAddClipWeight(builder, clipWeight)

# --- Slot 26: negative_prompt_for_image_prior (bool, default true) ---
def GenerationConfigurationAddNegativePromptForImagePrior(builder, val):
    builder.PrependBoolSlot(26, val, 1)

def AddNegativePromptForImagePrior(builder, val):
    GenerationConfigurationAddNegativePromptForImagePrior(builder, val)

# --- Slot 27: image_prior_steps (uint, default 5) ---
def GenerationConfigurationAddImagePriorSteps(builder, imagePriorSteps):
    builder.PrependUint32Slot(27, imagePriorSteps, 5)

def AddImagePriorSteps(builder, imagePriorSteps):
    GenerationConfigurationAddImagePriorSteps(builder, imagePriorSteps)

# --- Slot 28: refiner_model (string) ---
def GenerationConfigurationAddRefinerModel(builder, refinerModel):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(refinerModel), 0)

def AddRefinerModel(builder, refinerModel):
    GenerationConfigurationAddRefinerModel(builder, refinerModel)

# --- Slot 29: original_image_height (uint) ---
# NOTE: In config.fbs, height comes BEFORE width!
def GenerationConfigurationAddOriginalImageHeight(builder, originalImageHeight):
    builder.PrependUint32Slot(29, originalImageHeight, 0)

def AddOriginalImageHeight(builder, originalImageHeight):
    GenerationConfigurationAddOriginalImageHeight(builder, originalImageHeight)

# --- Slot 30: original_image_width (uint) ---
def GenerationConfigurationAddOriginalImageWidth(builder, originalImageWidth):
    builder.PrependUint32Slot(30, originalImageWidth, 0)

def AddOriginalImageWidth(builder, originalImageWidth):
    GenerationConfigurationAddOriginalImageWidth(builder, originalImageWidth)

# --- Slot 31: crop_top (int) ---
def GenerationConfigurationAddCropTop(builder, cropTop):
    builder.PrependInt32Slot(31, cropTop, 0)

def AddCropTop(builder, cropTop):
    GenerationConfigurationAddCropTop(builder, cropTop)

# --- Slot 32: crop_left (int) ---
def GenerationConfigurationAddCropLeft(builder, cropLeft):
    builder.PrependInt32Slot(32, cropLeft, 0)

def AddCropLeft(builder, cropLeft):
    GenerationConfigurationAddCropLeft(builder, cropLeft)

# --- Slot 33: target_image_height (uint) ---
# NOTE: In config.fbs, height comes BEFORE width!
def GenerationConfigurationAddTargetImageHeight(builder, targetImageHeight):
    builder.PrependUint32Slot(33, targetImageHeight, 0)

def AddTargetImageHeight(builder, targetImageHeight):
    GenerationConfigurationAddTargetImageHeight(builder, targetImageHeight)

# --- Slot 34: target_image_width (uint) ---
def GenerationConfigurationAddTargetImageWidth(builder, targetImageWidth):
    builder.PrependUint32Slot(34, targetImageWidth, 0)

def AddTargetImageWidth(builder, targetImageWidth):
    GenerationConfigurationAddTargetImageWidth(builder, targetImageWidth)

# --- Slot 35: aesthetic_score (float, default 6) ---
def GenerationConfigurationAddAestheticScore(builder, aestheticScore):
    builder.PrependFloat32Slot(35, aestheticScore, 6.0)

def AddAestheticScore(builder, aestheticScore):
    GenerationConfigurationAddAestheticScore(builder, aestheticScore)

# --- Slot 36: negative_aesthetic_score (float, default 2.5) ---
def GenerationConfigurationAddNegativeAestheticScore(builder, negativeAestheticScore):
    builder.PrependFloat32Slot(36, negativeAestheticScore, 2.5)

def AddNegativeAestheticScore(builder, negativeAestheticScore):
    GenerationConfigurationAddNegativeAestheticScore(builder, negativeAestheticScore)

# --- Slot 37: zero_negative_prompt (bool) ---
def GenerationConfigurationAddZeroNegativePrompt(builder, zeroNegativePrompt):
    builder.PrependBoolSlot(37, zeroNegativePrompt, 0)

def AddZeroNegativePrompt(builder, zeroNegativePrompt):
    GenerationConfigurationAddZeroNegativePrompt(builder, zeroNegativePrompt)

# --- Slot 38: refiner_start (float, default 0.7) ---
def GenerationConfigurationAddRefinerStart(builder, refinerStart):
    builder.PrependFloat32Slot(38, refinerStart, 0.7)

def AddRefinerStart(builder, refinerStart):
    GenerationConfigurationAddRefinerStart(builder, refinerStart)

# --- Slot 39: negative_original_image_height (uint) ---
def GenerationConfigurationAddNegativeOriginalImageHeight(builder, val):
    builder.PrependUint32Slot(39, val, 0)

def AddNegativeOriginalImageHeight(builder, val):
    GenerationConfigurationAddNegativeOriginalImageHeight(builder, val)

# --- Slot 40: negative_original_image_width (uint) ---
def GenerationConfigurationAddNegativeOriginalImageWidth(builder, val):
    builder.PrependUint32Slot(40, val, 0)

def AddNegativeOriginalImageWidth(builder, val):
    GenerationConfigurationAddNegativeOriginalImageWidth(builder, val)

# --- Slot 41: name (string) ---
def GenerationConfigurationAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(41, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    GenerationConfigurationAddName(builder, name)

# --- Slot 42: fps_id (uint, default 5) ---
def GenerationConfigurationAddFpsId(builder, fpsId):
    builder.PrependUint32Slot(42, fpsId, 5)

def AddFpsId(builder, fpsId):
    GenerationConfigurationAddFpsId(builder, fpsId)

# --- Slot 43: motion_bucket_id (uint, default 127) ---
def GenerationConfigurationAddMotionBucketId(builder, motionBucketId):
    builder.PrependUint32Slot(43, motionBucketId, 127)

def AddMotionBucketId(builder, motionBucketId):
    GenerationConfigurationAddMotionBucketId(builder, motionBucketId)

# --- Slot 44: cond_aug (float, default 0.02) ---
def GenerationConfigurationAddCondAug(builder, condAug):
    builder.PrependFloat32Slot(44, condAug, 0.02)

def AddCondAug(builder, condAug):
    GenerationConfigurationAddCondAug(builder, condAug)

# --- Slot 45: start_frame_cfg (float, default 1.0) ---
def GenerationConfigurationAddStartFrameCfg(builder, startFrameCfg):
    builder.PrependFloat32Slot(45, startFrameCfg, 1.0)

def AddStartFrameCfg(builder, startFrameCfg):
    GenerationConfigurationAddStartFrameCfg(builder, startFrameCfg)

# --- Slot 46: num_frames (uint, default 14) ---
def GenerationConfigurationAddNumFrames(builder, numFrames):
    builder.PrependUint32Slot(46, numFrames, 14)

def AddNumFrames(builder, numFrames):
    GenerationConfigurationAddNumFrames(builder, numFrames)

# --- Slot 47: mask_blur_outset (int) ---
def GenerationConfigurationAddMaskBlurOutset(builder, maskBlurOutset):
    builder.PrependInt32Slot(47, maskBlurOutset, 0)

def AddMaskBlurOutset(builder, maskBlurOutset):
    GenerationConfigurationAddMaskBlurOutset(builder, maskBlurOutset)

# --- Slot 48: sharpness (float) ---
def GenerationConfigurationAddSharpness(builder, sharpness):
    builder.PrependFloat32Slot(48, sharpness, 0.0)

def AddSharpness(builder, sharpness):
    GenerationConfigurationAddSharpness(builder, sharpness)

# --- Slot 49: shift (float, default 1.0) ---
def GenerationConfigurationAddShift(builder, shift):
    builder.PrependFloat32Slot(49, shift, 1.0)

def AddShift(builder, shift):
    GenerationConfigurationAddShift(builder, shift)

# --- Slot 50: stage_2_steps (uint, default 10) ---
def GenerationConfigurationAddStage2Steps(builder, stage2Steps):
    builder.PrependUint32Slot(50, stage2Steps, 10)

def AddStage2Steps(builder, stage2Steps):
    GenerationConfigurationAddStage2Steps(builder, stage2Steps)

# --- Slot 51: stage_2_cfg (float, default 1.0) ---
def GenerationConfigurationAddStage2Cfg(builder, stage2Cfg):
    builder.PrependFloat32Slot(51, stage2Cfg, 1.0)

def AddStage2Cfg(builder, stage2Cfg):
    GenerationConfigurationAddStage2Cfg(builder, stage2Cfg)

# --- Slot 52: stage_2_shift (float, default 1.0) ---
def GenerationConfigurationAddStage2Shift(builder, stage2Shift):
    builder.PrependFloat32Slot(52, stage2Shift, 1.0)

def AddStage2Shift(builder, stage2Shift):
    GenerationConfigurationAddStage2Shift(builder, stage2Shift)

# --- Slot 53: tiled_decoding (bool) ---
def GenerationConfigurationAddTiledDecoding(builder, tiledDecoding):
    builder.PrependBoolSlot(53, tiledDecoding, 0)

def AddTiledDecoding(builder, tiledDecoding):
    GenerationConfigurationAddTiledDecoding(builder, tiledDecoding)

# --- Slot 54: decoding_tile_width (ushort, default 10) ---
def GenerationConfigurationAddDecodingTileWidth(builder, decodingTileWidth):
    builder.PrependUint16Slot(54, decodingTileWidth, 10)

def AddDecodingTileWidth(builder, decodingTileWidth):
    GenerationConfigurationAddDecodingTileWidth(builder, decodingTileWidth)

# --- Slot 55: decoding_tile_height (ushort, default 10) ---
def GenerationConfigurationAddDecodingTileHeight(builder, decodingTileHeight):
    builder.PrependUint16Slot(55, decodingTileHeight, 10)

def AddDecodingTileHeight(builder, decodingTileHeight):
    GenerationConfigurationAddDecodingTileHeight(builder, decodingTileHeight)

# --- Slot 56: decoding_tile_overlap (ushort, default 2) ---
def GenerationConfigurationAddDecodingTileOverlap(builder, decodingTileOverlap):
    builder.PrependUint16Slot(56, decodingTileOverlap, 2)

def AddDecodingTileOverlap(builder, decodingTileOverlap):
    GenerationConfigurationAddDecodingTileOverlap(builder, decodingTileOverlap)

# --- Slot 57: stochastic_sampling_gamma (float, default 0.3) ---
def GenerationConfigurationAddStochasticSamplingGamma(builder, stochasticSamplingGamma):
    builder.PrependFloat32Slot(57, stochasticSamplingGamma, 0.3)

def AddStochasticSamplingGamma(builder, stochasticSamplingGamma):
    GenerationConfigurationAddStochasticSamplingGamma(builder, stochasticSamplingGamma)

# --- Slot 58: preserve_original_after_inpaint (bool, default true) ---
def GenerationConfigurationAddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint):
    builder.PrependBoolSlot(58, preserveOriginalAfterInpaint, 1)

def AddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint):
    GenerationConfigurationAddPreserveOriginalAfterInpaint(builder, preserveOriginalAfterInpaint)

# --- Slot 59: tiled_diffusion (bool) ---
def GenerationConfigurationAddTiledDiffusion(builder, tiledDiffusion):
    builder.PrependBoolSlot(59, tiledDiffusion, 0)

def AddTiledDiffusion(builder, tiledDiffusion):
    GenerationConfigurationAddTiledDiffusion(builder, tiledDiffusion)

# --- Slot 60: diffusion_tile_width (ushort, default 16) ---
def GenerationConfigurationAddDiffusionTileWidth(builder, diffusionTileWidth):
    builder.PrependUint16Slot(60, diffusionTileWidth, 16)

def AddDiffusionTileWidth(builder, diffusionTileWidth):
    GenerationConfigurationAddDiffusionTileWidth(builder, diffusionTileWidth)

# --- Slot 61: diffusion_tile_height (ushort, default 16) ---
def GenerationConfigurationAddDiffusionTileHeight(builder, diffusionTileHeight):
    builder.PrependUint16Slot(61, diffusionTileHeight, 16)

def AddDiffusionTileHeight(builder, diffusionTileHeight):
    GenerationConfigurationAddDiffusionTileHeight(builder, diffusionTileHeight)

# --- Slot 62: diffusion_tile_overlap (ushort, default 2) ---
def GenerationConfigurationAddDiffusionTileOverlap(builder, diffusionTileOverlap):
    builder.PrependUint16Slot(62, diffusionTileOverlap, 2)

def AddDiffusionTileOverlap(builder, diffusionTileOverlap):
    GenerationConfigurationAddDiffusionTileOverlap(builder, diffusionTileOverlap)

# --- Slot 63: upscaler_scale_factor (ubyte) ---
def GenerationConfigurationAddUpscalerScaleFactor(builder, upscalerScaleFactor):
    builder.PrependUint8Slot(63, upscalerScaleFactor, 0)

def AddUpscalerScaleFactor(builder, upscalerScaleFactor):
    GenerationConfigurationAddUpscalerScaleFactor(builder, upscalerScaleFactor)

# --- Slot 64: t5_text_encoder (bool, default true) ---
def GenerationConfigurationAddT5TextEncoder(builder, t5TextEncoder):
    builder.PrependBoolSlot(64, t5TextEncoder, 1)

def AddT5TextEncoder(builder, t5TextEncoder):
    GenerationConfigurationAddT5TextEncoder(builder, t5TextEncoder)

# --- Slot 65: separate_clip_l (bool) ---
def GenerationConfigurationAddSeparateClipL(builder, separateClipL):
    builder.PrependBoolSlot(65, separateClipL, 0)

def AddSeparateClipL(builder, separateClipL):
    GenerationConfigurationAddSeparateClipL(builder, separateClipL)

# --- Slot 66: clip_l_text (string) ---
def GenerationConfigurationAddClipLText(builder, clipLText):
    builder.PrependUOffsetTRelativeSlot(66, flatbuffers.number_types.UOffsetTFlags.py_type(clipLText), 0)

def AddClipLText(builder, clipLText):
    GenerationConfigurationAddClipLText(builder, clipLText)

# --- Slot 67: separate_open_clip_g (bool) ---
def GenerationConfigurationAddSeparateOpenClipG(builder, separateOpenClipG):
    builder.PrependBoolSlot(67, separateOpenClipG, 0)

def AddSeparateOpenClipG(builder, separateOpenClipG):
    GenerationConfigurationAddSeparateOpenClipG(builder, separateOpenClipG)

# --- Slot 68: open_clip_g_text (string) ---
def GenerationConfigurationAddOpenClipGText(builder, openClipGText):
    builder.PrependUOffsetTRelativeSlot(68, flatbuffers.number_types.UOffsetTFlags.py_type(openClipGText), 0)

def AddOpenClipGText(builder, openClipGText):
    GenerationConfigurationAddOpenClipGText(builder, openClipGText)

# --- Slot 69: speed_up_with_guidance_embed (bool, default true) ---
def GenerationConfigurationAddSpeedUpWithGuidanceEmbed(builder, speedUpWithGuidanceEmbed):
    builder.PrependBoolSlot(69, speedUpWithGuidanceEmbed, 1)

def AddSpeedUpWithGuidanceEmbed(builder, speedUpWithGuidanceEmbed):
    GenerationConfigurationAddSpeedUpWithGuidanceEmbed(builder, speedUpWithGuidanceEmbed)

# --- Slot 70: guidance_embed (float, default 3.5) ---
def GenerationConfigurationAddGuidanceEmbed(builder, guidanceEmbed):
    builder.PrependFloat32Slot(70, guidanceEmbed, 3.5)

def AddGuidanceEmbed(builder, guidanceEmbed):
    GenerationConfigurationAddGuidanceEmbed(builder, guidanceEmbed)

# --- Slot 71: resolution_dependent_shift (bool, default true) ---
def GenerationConfigurationAddResolutionDependentShift(builder, resolutionDependentShift):
    builder.PrependBoolSlot(71, resolutionDependentShift, 1)

def AddResolutionDependentShift(builder, resolutionDependentShift):
    GenerationConfigurationAddResolutionDependentShift(builder, resolutionDependentShift)

# --- Slot 72: tea_cache_start (int, default 5) ---
def GenerationConfigurationAddTeaCacheStart(builder, teaCacheStart):
    builder.PrependInt32Slot(72, teaCacheStart, 5)

def AddTeaCacheStart(builder, teaCacheStart):
    GenerationConfigurationAddTeaCacheStart(builder, teaCacheStart)

# --- Slot 73: tea_cache_end (int, default -1) ---
def GenerationConfigurationAddTeaCacheEnd(builder, teaCacheEnd):
    builder.PrependInt32Slot(73, teaCacheEnd, -1)

def AddTeaCacheEnd(builder, teaCacheEnd):
    GenerationConfigurationAddTeaCacheEnd(builder, teaCacheEnd)

# --- Slot 74: tea_cache_threshold (float, default 0.06) ---
def GenerationConfigurationAddTeaCacheThreshold(builder, teaCacheThreshold):
    builder.PrependFloat32Slot(74, teaCacheThreshold, 0.06)

def AddTeaCacheThreshold(builder, teaCacheThreshold):
    GenerationConfigurationAddTeaCacheThreshold(builder, teaCacheThreshold)

# --- Slot 75: tea_cache (bool) ---
def GenerationConfigurationAddTeaCache(builder, teaCache):
    builder.PrependBoolSlot(75, teaCache, 0)

def AddTeaCache(builder, teaCache):
    GenerationConfigurationAddTeaCache(builder, teaCache)

# --- Slot 76: separate_t5 (bool) ---
def GenerationConfigurationAddSeparateT5(builder, separateT5):
    builder.PrependBoolSlot(76, separateT5, 0)

def AddSeparateT5(builder, separateT5):
    GenerationConfigurationAddSeparateT5(builder, separateT5)

# --- Slot 77: t5_text (string) ---
def GenerationConfigurationAddT5Text(builder, t5Text):
    builder.PrependUOffsetTRelativeSlot(77, flatbuffers.number_types.UOffsetTFlags.py_type(t5Text), 0)

def AddT5Text(builder, t5Text):
    GenerationConfigurationAddT5Text(builder, t5Text)

# --- Slot 78: tea_cache_max_skip_steps (int, default 3) ---
def GenerationConfigurationAddTeaCacheMaxSkipSteps(builder, teaCacheMaxSkipSteps):
    builder.PrependInt32Slot(78, teaCacheMaxSkipSteps, 3)

def AddTeaCacheMaxSkipSteps(builder, teaCacheMaxSkipSteps):
    GenerationConfigurationAddTeaCacheMaxSkipSteps(builder, teaCacheMaxSkipSteps)

# --- Slot 79: causal_inference_enabled (bool) ---
def GenerationConfigurationAddCausalInferenceEnabled(builder, causalInferenceEnabled):
    builder.PrependBoolSlot(79, causalInferenceEnabled, 0)

def AddCausalInferenceEnabled(builder, causalInferenceEnabled):
    GenerationConfigurationAddCausalInferenceEnabled(builder, causalInferenceEnabled)

# --- Slot 80: causal_inference (int, default 3) ---
def GenerationConfigurationAddCausalInference(builder, causalInference):
    builder.PrependInt32Slot(80, causalInference, 3)

def AddCausalInference(builder, causalInference):
    GenerationConfigurationAddCausalInference(builder, causalInference)

# --- Slot 81: causal_inference_pad (int) ---
def GenerationConfigurationAddCausalInferencePad(builder, causalInferencePad):
    builder.PrependInt32Slot(81, causalInferencePad, 0)

def AddCausalInferencePad(builder, causalInferencePad):
    GenerationConfigurationAddCausalInferencePad(builder, causalInferencePad)

# --- Slot 82: cfg_zero_star (bool) ---
def GenerationConfigurationAddCfgZeroStar(builder, cfgZeroStar):
    builder.PrependBoolSlot(82, cfgZeroStar, 0)

def AddCfgZeroStar(builder, cfgZeroStar):
    GenerationConfigurationAddCfgZeroStar(builder, cfgZeroStar)

# --- Slot 83: cfg_zero_init_steps (int) ---
def GenerationConfigurationAddCfgZeroInitSteps(builder, cfgZeroInitSteps):
    builder.PrependInt32Slot(83, cfgZeroInitSteps, 0)

def AddCfgZeroInitSteps(builder, cfgZeroInitSteps):
    GenerationConfigurationAddCfgZeroInitSteps(builder, cfgZeroInitSteps)
