# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoRA(object):

    # LoRA
    def __init__(self):
        self._tab = flatbuffers.Table()

    @staticmethod
    def GetRootAs(buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoRA()
        x.Init(buf, n + offset)
        return x

    # LoRA
    def Init(self, buf, pos):
        self._tab.Buf = buf
        self._tab.Pos = pos

    # LoRA
    def File(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoRA
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.6

    # LoRA
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def Start(builder):
    builder.StartObject(3)

def AddFile(builder, file):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(file), 0)

def AddWeight(builder, weight):
    builder.PrependFloat32Slot(1, weight, 0.6)

def AddMode(builder, mode):
    builder.PrependUint8Slot(2, mode, 0)

def End(builder):
    return builder.EndObject()
